version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 2
    ports:
      - "5050-5051:5050"
    networks:
      - clycon_network

  nginx:
    container_name: main_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./utils/public:/var/www/utils
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - clycon_network

networks:
  clycon_network:
    name: clycon_network

