name: Deploy Fauno ExpressJS Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env.production
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          S3_ID: ${{ secrets.S3_ID }}
          S3_KEY: ${{ secrets.S3_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SMS_AERO_URL: ${{ secrets.SMS_AERO_URL }}
          SMS_AERO_LOGIN: ${{ secrets.SMS_AERO_LOGIN }}
          SMS_AERO_TOKEN: ${{ secrets.SMS_AERO_TOKEN }}
          CP_PUBLIC_ID: ${{ secrets.CP_PUBLIC_ID }}
          CP_PRIVATE_KEY: ${{ secrets.CP_PRIVATE_KEY }}
        run: |
          cat <<EOF > .env.production
          DB_NAME=$DB_NAME
          DB_USER=$DB_USER
          DB_PASSWORD=$DB_PASSWORD
          DB_HOST=$DB_HOST
          DB_PORT=$DB_PORT

          S3_ID=$S3_ID
          S3_KEY=$S3_KEY
          
          SECRET_KEY=$SECRET_KEY
          SMS_AERO_URL=$SMS_AERO_URL
          SMS_AERO_LOGIN=$SMS_AERO_LOGIN
          SMS_AERO_TOKEN=$SMS_AERO_TOKEN
          
          CP_PUBLIC_ID=$CP_PUBLIC_ID
          CP_PRIVATE_KEY=$CP_PRIVATE_KEY
          EOF
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        run: bash ./deploy.sh
